{% set name = "yarn" %}
{% set version = "1.22.22" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha1: ac34549e6aa8e7ead463a7407e1c7390f61a6610

build:
  number: 0
  # nodejs isn't available on s390x
  skip: True # [linux and s390x]

requirements:
  run:
    - nodejs

test:
  commands:
    - yarn --version
    - yarn versions

about:
  home: https://yarnpkg.com
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fast, reliable, and secure dependency management.
  description: |
    Yarn is a package manager for your code. It allows you to use and share
    code with other developers from around the world. Yarn does this
    quickly, securely, and reliably so you don’t ever have to worry.
  doc_url: https://github.com/yarnpkg/yarn/docs
  dev_url: https://github.com/yarnpkg/yarn

extra:
  recipe-maintainers:
    - dfroger
    - bollwyvl
