travis:
  secure:
    BINSTAR_TOKEN: d93vD5INVCIcEafOjijOA8r/7bfw3NAu30xtcxS7fYN4wILNbRpv0MPKHlSUXG9R7AL/+6vl3AN7FZlZX2S/sGcDT4Fkg2qnjw1iZ9QmjghclkFUYrSIvEJIgO5J2TLxt4LBe6S61U5o16qPcjIA47MFEVGvRzZd47o5uNRkt96VnKvfkacLgKAz3jtwsYL8UZHDbhuEoJc5mxgZBFiQA/Ux7jH8TdHQ97XPgN3vUeyEMFx6L/DHNt7XbX8mrYvIjlAOEhDipWmhBiZEhLVi+jNASZyT6hDo7mH0gSKQ3d556ABo1H/AYLLZgBJZawlQ3ng3J6suEqFLTqYWtREwqVf57GlmHYDAXtVkpmsNxRT89ydssW+SyqZ8pQYvnYpabKTONZ8+FM/2d/ltRrM1S0y035L/gS6gQBvyuOnN2qKgLa4335Jx2j/9E18xUxs+L1Nz2N4pO19JHZNzc6y9UBZrBLYTY/Z8w/Rcy+U7jWwNpyiedLTmcSgYcG1u9pj+B1hFU2fxFzxqEqplZ5OgXKOEEtg24jcXKz0lzUrwTuLarjigDFr3m/hqdGSEk22ELq6Cg/YUUUFjCch2rKmYwjCuF+vS+WlPhzxhsfN3g3dUDbyEy2/W2YtOryIXxRDxMPTMFqIC2PqZMEy9Yq2qMrX3+To4YgNWojhJ0RPB9sk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
