travis:
  secure:
    BINSTAR_TOKEN: a8fAB0zm5g8ZocrWOM946bDhFwc4SbuMzj5sWRCDWe9XTKE7a+JPExXDgq2ghedXbTUU3ACyyHOIZqw47UA/dyTKVKoTqOP3SPCNYYLRA6tIGu6yCn1Il2PZG60rxA9exkksO5/SVhMmAspo7i5Rkg3qdjyB2iKq49kKftvfyIro6jyDLc//Lh+KZiG3x8Lx9HLgnaD+smkNmsvObM9x0p0sBG84OARq+iiNkw4v3NJpBKnNgXvLQeTPSHUQp1tIQsNbrfFq+j0syOeLdVXYUm4E/7RwD3GlcGBcLI6klA8viGMl7OhQqeVo93rX7G0FqnP7beX9zaVBSxlk9/+4/Cb2mvj7YJ7BspvIiu9TxS3kR56UG7fK2wIufl8qol2xRx/NVCdgwCxGZpiH1hd3EN2AQCT6+Ohu3+L/LCP9El1ioOfOku7Uf3udrStES8ldILTRjPSYv0lRHPJgYApPy8M765uxXApb0LuWgoi41FiO0q+iNr5n2mN5qdg/oqYQUAmdfQG81aYCvfr/SEK689+Hcbg8pxXwg3VF2yY4lQSuqqW5lrU1agdaSkLD+FMTm2oVSxKcbVBVAc8T3MP56ZY5y/+rjloqA93EWHIBj77iUppRMiIWR2TIUwNaMImb5+ARnGROv6m7bz1x+vPpLm4gYHh2+gqTcBB6hE5mMbE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
